// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { AckDeviceEventData, AckDeviceEventErrors, AckDeviceEventResponses, AnalyzeDeviceData, AnalyzeDeviceErrors, AnalyzeDeviceResponses, AnalyzeLatestPoseData, AnalyzeLatestPoseErrors, AnalyzeLatestPoseResponses, DeviceEventsData, DeviceEventsErrors, DeviceEventsResponses, GetAutopilotStateData, GetAutopilotStateErrors, GetAutopilotStateResponses, HealthData, HealthResponses, LatestDeviceStateData, LatestDeviceStateErrors, LatestDeviceStateResponses, ListDevicesData, ListDevicesResponses, SendCommandData, SendCommandErrors, SendCommandResponses, TelemetryHistoryBucketedData, TelemetryHistoryBucketedErrors, TelemetryHistoryBucketedResponses, TelemetryHistoryData, TelemetryHistoryErrors, TelemetryHistoryResponses, UpdateAutopilotStateData, UpdateAutopilotStateErrors, UpdateAutopilotStateResponses, UploadImageData, UploadImageErrors, UploadImageResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List Devices
 */
export const listDevices = <ThrowOnError extends boolean = false>(options?: Options<ListDevicesData, ThrowOnError>): RequestResult<ListDevicesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListDevicesResponses, unknown, ThrowOnError>({ url: '/api/devices', ...options });

/**
 * Analyze Device
 */
export const analyzeDevice = <ThrowOnError extends boolean = false>(options: Options<AnalyzeDeviceData, ThrowOnError>): RequestResult<AnalyzeDeviceResponses, AnalyzeDeviceErrors, ThrowOnError> => (options.client ?? client).post<AnalyzeDeviceResponses, AnalyzeDeviceErrors, ThrowOnError>({ url: '/api/devices/{device_id}/ai/analyze', ...options });

/**
 * Get Autopilot State
 */
export const getAutopilotState = <ThrowOnError extends boolean = false>(options: Options<GetAutopilotStateData, ThrowOnError>): RequestResult<GetAutopilotStateResponses, GetAutopilotStateErrors, ThrowOnError> => (options.client ?? client).get<GetAutopilotStateResponses, GetAutopilotStateErrors, ThrowOnError>({ url: '/api/devices/{device_id}/autopilot', ...options });

/**
 * Update Autopilot State
 */
export const updateAutopilotState = <ThrowOnError extends boolean = false>(options: Options<UpdateAutopilotStateData, ThrowOnError>): RequestResult<UpdateAutopilotStateResponses, UpdateAutopilotStateErrors, ThrowOnError> => (options.client ?? client).put<UpdateAutopilotStateResponses, UpdateAutopilotStateErrors, ThrowOnError>({
    url: '/api/devices/{device_id}/autopilot',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Send Command
 */
export const sendCommand = <ThrowOnError extends boolean = false>(options: Options<SendCommandData, ThrowOnError>): RequestResult<SendCommandResponses, SendCommandErrors, ThrowOnError> => (options.client ?? client).post<SendCommandResponses, SendCommandErrors, ThrowOnError>({
    url: '/api/devices/{device_id}/commands',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Device Events
 */
export const deviceEvents = <ThrowOnError extends boolean = false>(options: Options<DeviceEventsData, ThrowOnError>): RequestResult<DeviceEventsResponses, DeviceEventsErrors, ThrowOnError> => (options.client ?? client).get<DeviceEventsResponses, DeviceEventsErrors, ThrowOnError>({ url: '/api/devices/{device_id}/events', ...options });

/**
 * Ack Device Event
 */
export const ackDeviceEvent = <ThrowOnError extends boolean = false>(options: Options<AckDeviceEventData, ThrowOnError>): RequestResult<AckDeviceEventResponses, AckDeviceEventErrors, ThrowOnError> => (options.client ?? client).post<AckDeviceEventResponses, AckDeviceEventErrors, ThrowOnError>({ url: '/api/devices/{device_id}/events/{event_id}/ack', ...options });

/**
 * Telemetry History
 */
export const telemetryHistory = <ThrowOnError extends boolean = false>(options: Options<TelemetryHistoryData, ThrowOnError>): RequestResult<TelemetryHistoryResponses, TelemetryHistoryErrors, ThrowOnError> => (options.client ?? client).get<TelemetryHistoryResponses, TelemetryHistoryErrors, ThrowOnError>({ url: '/api/devices/{device_id}/history', ...options });

/**
 * Telemetry History Bucketed
 */
export const telemetryHistoryBucketed = <ThrowOnError extends boolean = false>(options: Options<TelemetryHistoryBucketedData, ThrowOnError>): RequestResult<TelemetryHistoryBucketedResponses, TelemetryHistoryBucketedErrors, ThrowOnError> => (options.client ?? client).get<TelemetryHistoryBucketedResponses, TelemetryHistoryBucketedErrors, ThrowOnError>({ url: '/api/devices/{device_id}/history/bucketed', ...options });

/**
 * Upload Image
 */
export const uploadImage = <ThrowOnError extends boolean = false>(options: Options<UploadImageData, ThrowOnError>): RequestResult<UploadImageResponses, UploadImageErrors, ThrowOnError> => (options.client ?? client).post<UploadImageResponses, UploadImageErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/devices/{device_id}/images',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Latest Device State
 */
export const latestDeviceState = <ThrowOnError extends boolean = false>(options: Options<LatestDeviceStateData, ThrowOnError>): RequestResult<LatestDeviceStateResponses, LatestDeviceStateErrors, ThrowOnError> => (options.client ?? client).get<LatestDeviceStateResponses, LatestDeviceStateErrors, ThrowOnError>({ url: '/api/devices/{device_id}/latest', ...options });

/**
 * Analyze Latest Pose
 */
export const analyzeLatestPose = <ThrowOnError extends boolean = false>(options: Options<AnalyzeLatestPoseData, ThrowOnError>): RequestResult<AnalyzeLatestPoseResponses, AnalyzeLatestPoseErrors, ThrowOnError> => (options.client ?? client).post<AnalyzeLatestPoseResponses, AnalyzeLatestPoseErrors, ThrowOnError>({ url: '/api/devices/{device_id}/pose/analyze', ...options });

/**
 * Health
 */
export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>): RequestResult<HealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });
