// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AiAnalyzingEnvelope
 */
export type AiAnalyzingEnvelope = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Occurred At
     */
    occurred_at: string;
    payload: AiAnalyzingPayload;
    /**
     * Type
     */
    type: 'ai_analyzing';
};

/**
 * AiAnalyzingPayload
 */
export type AiAnalyzingPayload = {
    /**
     * Trigger
     */
    trigger: string;
};

/**
 * AiDecisionOut
 */
export type AiDecisionOut = {
    command: CommandOut;
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Image Attached
     */
    image_attached: boolean;
    /**
     * Model
     */
    model: string;
    /**
     * Published
     */
    published: boolean;
    /**
     * Reason
     */
    reason: string;
    /**
     * Risk Level
     */
    risk_level: 'low' | 'medium' | 'high' | 'unknown';
    /**
     * Trigger
     */
    trigger: string;
};

/**
 * AiResultEnvelope
 */
export type AiResultEnvelope = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Occurred At
     */
    occurred_at: string;
    payload: AiDecisionOut;
    /**
     * Type
     */
    type: 'ai_result';
};

/**
 * AiResultInfo
 */
export type AiResultInfo = {
    /**
     * Command Id
     */
    command_id: string;
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Model
     */
    model: string;
    /**
     * Reason
     */
    reason: string;
    /**
     * Risk Level
     */
    risk_level: string;
    /**
     * Summary
     */
    summary: string;
};

/**
 * AutopilotEnabled
 */
export type AutopilotEnabled = {
    /**
     * Enabled
     */
    enabled: boolean;
};

/**
 * AutopilotEnvelope
 */
export type AutopilotEnvelope = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Occurred At
     */
    occurred_at: string;
    payload: AutopilotState;
    /**
     * Type
     */
    type: 'autopilot';
};

/**
 * AutopilotIn
 */
export type AutopilotIn = {
    /**
     * Enabled
     */
    enabled: boolean;
};

/**
 * AutopilotState
 */
export type AutopilotState = {
    /**
     * Cooldown Seconds
     */
    cooldown_seconds: number;
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Min Confidence
     */
    min_confidence: number;
    /**
     * Trigger Levels
     */
    trigger_levels: Array<string>;
};

/**
 * Body_upload_image
 */
export type BodyUploadImage = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * CommandAckEnvelope
 */
export type CommandAckEnvelope = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Occurred At
     */
    occurred_at: string;
    payload: CommandAckPayload;
    /**
     * Type
     */
    type: 'command_ack';
};

/**
 * CommandAckPayload
 */
export type CommandAckPayload = {
    /**
     * Command Id
     */
    command_id: string;
    /**
     * Executed At
     */
    executed_at?: string | null;
    /**
     * Known Command
     */
    known_command?: boolean;
    /**
     * Message
     */
    message?: string;
    /**
     * Status
     */
    status: string;
    [key: string]: unknown;
};

/**
 * CommandEnvelope
 */
export type CommandEnvelope = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Occurred At
     */
    occurred_at: string;
    payload: CommandOut;
    /**
     * Type
     */
    type: 'command';
};

/**
 * CommandIn
 */
export type CommandIn = {
    /**
     * Parameter
     */
    parameter?: {
        [key: string]: unknown;
    };
    /**
     * Reason
     */
    reason?: string;
    /**
     * Type
     */
    type: 'none' | 'window.open' | 'window.close' | 'alarm.on' | 'alarm.off' | 'display.message';
};

/**
 * CommandOut
 */
export type CommandOut = {
    /**
     * Command Id
     */
    command_id: string;
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Executed At
     */
    executed_at?: string | null;
    /**
     * Parameter
     */
    parameter?: {
        [key: string]: unknown;
    };
    /**
     * Published At
     */
    published_at?: string | null;
    /**
     * Reason
     */
    reason: string;
    /**
     * Source
     */
    source: string;
    /**
     * Status
     */
    status: string;
    /**
     * Type
     */
    type: string;
};

/**
 * DeviceStatePayload
 */
export type DeviceStatePayload = {
    /**
     * Alarm On
     */
    alarm_on?: boolean | null;
    /**
     * Manual Override
     */
    manual_override?: boolean | null;
    /**
     * Window Open
     */
    window_open?: boolean | null;
};

/**
 * DeviceSummary
 */
export type DeviceSummary = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Last Seen At
     */
    last_seen_at?: string | null;
    /**
     * Status
     */
    status: string;
};

/**
 * ErrorEnvelope
 */
export type ErrorEnvelope = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Occurred At
     */
    occurred_at: string;
    payload: ErrorPayload;
    /**
     * Type
     */
    type: 'error';
};

/**
 * ErrorPayload
 */
export type ErrorPayload = {
    /**
     * Error
     */
    error: string;
    /**
     * Payload
     */
    payload?: {
        [key: string]: unknown;
    };
    /**
     * Topic
     */
    topic: string;
};

/**
 * EventEnvelope
 */
export type EventEnvelope = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Occurred At
     */
    occurred_at: string;
    payload: EventPayload;
    /**
     * Type
     */
    type: 'event';
};

/**
 * EventPayload
 */
export type EventPayload = {
    /**
     * Message
     */
    message?: string | null;
    /**
     * Severity
     */
    severity?: string | null;
    /**
     * Type
     */
    type?: string | null;
    [key: string]: unknown;
};

/**
 * FusionSnapshot
 */
export type FusionSnapshot = {
    /**
     * Air Quality
     */
    air_quality?: string | null;
    /**
     * Alarm Enabled
     */
    alarm_enabled?: boolean | null;
    /**
     * Reason
     */
    reason?: string | null;
    /**
     * Recommend Open Window
     */
    recommend_open_window?: boolean | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthOut
 */
export type HealthOut = {
    /**
     * Service
     */
    service: string;
    /**
     * Status
     */
    status: string;
};

/**
 * ImageAssetOut
 */
export type ImageAssetOut = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Id
     */
    id: number;
    /**
     * Url
     */
    url: string;
};

/**
 * ImageEnvelope
 */
export type ImageEnvelope = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Occurred At
     */
    occurred_at: string;
    payload: ImageSnapshot;
    /**
     * Type
     */
    type: 'image';
};

/**
 * ImageSnapshot
 */
export type ImageSnapshot = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: number;
    /**
     * Url
     */
    url: string;
};

/**
 * LatestState
 */
export type LatestState = {
    ai_result?: AiResultInfo | null;
    autopilot?: AutopilotEnabled | null;
    command?: CommandOut | null;
    device: DeviceSummary;
    image?: ImageSnapshot | null;
    telemetry?: TelemetryPoint | null;
};

/**
 * LogEnvelope
 */
export type LogEnvelope = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Occurred At
     */
    occurred_at: string;
    /**
     * Payload
     */
    payload?: {
        [key: string]: unknown;
    };
    /**
     * Type
     */
    type: 'log';
};

/**
 * SensorPayload
 */
export type SensorPayload = {
    /**
     * Eco2 Ppm
     */
    eco2_ppm?: number | null;
    /**
     * Hcho Ug M3
     */
    hcho_ug_m3?: number | null;
    /**
     * Humidity Percent
     */
    humidity_percent?: number | null;
    /**
     * Light Is Dark
     */
    light_is_dark?: boolean | null;
    /**
     * Temperature C
     */
    temperature_c?: number | null;
    /**
     * Tvoc Ppb
     */
    tvoc_ppb?: number | null;
};

/**
 * StatusEnvelope
 */
export type StatusEnvelope = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Occurred At
     */
    occurred_at: string;
    payload: StatusPayload;
    /**
     * Type
     */
    type: 'status';
};

/**
 * StatusPayload
 */
export type StatusPayload = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Last Seen At
     */
    last_seen_at?: string | null;
    /**
     * Status
     */
    status: string;
};

/**
 * TelemetryBucketPoint
 *
 * time_bucket 降采样后的遥测聚合点（数值取均值，布尔取或，air_quality 取最差档）。
 */
export type TelemetryBucketPoint = {
    /**
     * Air Quality
     */
    air_quality?: string | null;
    /**
     * Alarm On
     */
    alarm_on?: boolean | null;
    /**
     * Bucket
     */
    bucket: string;
    /**
     * Eco2 Ppm
     */
    eco2_ppm?: number | null;
    /**
     * Hcho Ug M3
     */
    hcho_ug_m3?: number | null;
    /**
     * Humidity Percent
     */
    humidity_percent?: number | null;
    /**
     * Sample Count
     */
    sample_count: number;
    /**
     * Temperature C
     */
    temperature_c?: number | null;
    /**
     * Tvoc Ppb
     */
    tvoc_ppb?: number | null;
    /**
     * Window Open
     */
    window_open?: boolean | null;
};

/**
 * TelemetryEnvelope
 */
export type TelemetryEnvelope = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Occurred At
     */
    occurred_at: string;
    payload: TelemetryPoint;
    /**
     * Type
     */
    type: 'telemetry';
};

/**
 * TelemetryPoint
 */
export type TelemetryPoint = {
    /**
     * Device Id
     */
    device_id: string;
    fusion: FusionSnapshot;
    /**
     * Sampled At
     */
    sampled_at: string;
    sensors: SensorPayload;
    state: DeviceStatePayload;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type WsMessage = ({
    type: 'telemetry';
} & TelemetryEnvelope) | ({
    type: 'status';
} & StatusEnvelope) | ({
    type: 'image';
} & ImageEnvelope) | ({
    type: 'command';
} & CommandEnvelope) | ({
    type: 'command_ack';
} & CommandAckEnvelope) | ({
    type: 'event';
} & EventEnvelope) | ({
    type: 'log';
} & LogEnvelope) | ({
    type: 'error';
} & ErrorEnvelope) | ({
    type: 'ai_analyzing';
} & AiAnalyzingEnvelope) | ({
    type: 'ai_result';
} & AiResultEnvelope) | ({
    type: 'autopilot';
} & AutopilotEnvelope);

export type ListDevicesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/devices';
};

export type ListDevicesResponses = {
    /**
     * Response List Devices
     *
     * Successful Response
     */
    200: Array<DeviceSummary>;
};

export type ListDevicesResponse = ListDevicesResponses[keyof ListDevicesResponses];

export type AnalyzeDeviceData = {
    body?: never;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: never;
    url: '/api/devices/{device_id}/ai/analyze';
};

export type AnalyzeDeviceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalyzeDeviceError = AnalyzeDeviceErrors[keyof AnalyzeDeviceErrors];

export type AnalyzeDeviceResponses = {
    /**
     * Successful Response
     */
    200: AiDecisionOut;
};

export type AnalyzeDeviceResponse = AnalyzeDeviceResponses[keyof AnalyzeDeviceResponses];

export type GetAutopilotStateData = {
    body?: never;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: never;
    url: '/api/devices/{device_id}/autopilot';
};

export type GetAutopilotStateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAutopilotStateError = GetAutopilotStateErrors[keyof GetAutopilotStateErrors];

export type GetAutopilotStateResponses = {
    /**
     * Successful Response
     */
    200: AutopilotState;
};

export type GetAutopilotStateResponse = GetAutopilotStateResponses[keyof GetAutopilotStateResponses];

export type UpdateAutopilotStateData = {
    body: AutopilotIn;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: never;
    url: '/api/devices/{device_id}/autopilot';
};

export type UpdateAutopilotStateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAutopilotStateError = UpdateAutopilotStateErrors[keyof UpdateAutopilotStateErrors];

export type UpdateAutopilotStateResponses = {
    /**
     * Successful Response
     */
    200: AutopilotState;
};

export type UpdateAutopilotStateResponse = UpdateAutopilotStateResponses[keyof UpdateAutopilotStateResponses];

export type SendCommandData = {
    body: CommandIn;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: never;
    url: '/api/devices/{device_id}/commands';
};

export type SendCommandErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendCommandError = SendCommandErrors[keyof SendCommandErrors];

export type SendCommandResponses = {
    /**
     * Successful Response
     */
    200: CommandOut;
};

export type SendCommandResponse = SendCommandResponses[keyof SendCommandResponses];

export type TelemetryHistoryData = {
    body?: never;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/devices/{device_id}/history';
};

export type TelemetryHistoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TelemetryHistoryError = TelemetryHistoryErrors[keyof TelemetryHistoryErrors];

export type TelemetryHistoryResponses = {
    /**
     * Response Telemetry History
     *
     * Successful Response
     */
    200: Array<TelemetryPoint>;
};

export type TelemetryHistoryResponse = TelemetryHistoryResponses[keyof TelemetryHistoryResponses];

export type TelemetryHistoryBucketedData = {
    body?: never;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: {
        /**
         * Bucket
         *
         * 降采样窗口秒数
         */
        bucket?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/devices/{device_id}/history/bucketed';
};

export type TelemetryHistoryBucketedErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TelemetryHistoryBucketedError = TelemetryHistoryBucketedErrors[keyof TelemetryHistoryBucketedErrors];

export type TelemetryHistoryBucketedResponses = {
    /**
     * Response Telemetry History Bucketed
     *
     * Successful Response
     */
    200: Array<TelemetryBucketPoint>;
};

export type TelemetryHistoryBucketedResponse = TelemetryHistoryBucketedResponses[keyof TelemetryHistoryBucketedResponses];

export type UploadImageData = {
    body: BodyUploadImage;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: never;
    url: '/api/devices/{device_id}/images';
};

export type UploadImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadImageError = UploadImageErrors[keyof UploadImageErrors];

export type UploadImageResponses = {
    /**
     * Successful Response
     */
    200: ImageAssetOut;
};

export type UploadImageResponse = UploadImageResponses[keyof UploadImageResponses];

export type LatestDeviceStateData = {
    body?: never;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: never;
    url: '/api/devices/{device_id}/latest';
};

export type LatestDeviceStateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LatestDeviceStateError = LatestDeviceStateErrors[keyof LatestDeviceStateErrors];

export type LatestDeviceStateResponses = {
    /**
     * Successful Response
     */
    200: LatestState;
};

export type LatestDeviceStateResponse = LatestDeviceStateResponses[keyof LatestDeviceStateResponses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthResponses = {
    /**
     * Successful Response
     */
    200: HealthOut;
};

export type HealthResponse = HealthResponses[keyof HealthResponses];
