// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AiRunCreate
 */
export type AiRunCreate = {
    /**
     * Goal
     */
    goal?: string;
    /**
     * Image Id
     */
    image_id?: number | null;
    /**
     * Kind
     */
    kind: 'decision' | 'report' | 'vision' | 'patrol';
    /**
     * Period
     */
    period?: 'hour' | 'day' | 'week' | null;
    /**
     * Trigger
     */
    trigger?: 'manual' | 'event' | 'schedule' | 'patrol';
};

/**
 * AiRunOut
 */
export type AiRunOut = {
    /**
     * Attempt Count
     */
    attempt_count?: number;
    /**
     * Cancel Requested At
     */
    cancel_requested_at?: string | null;
    /**
     * Completed At
     */
    completed_at?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Error Code
     */
    error_code?: string | null;
    /**
     * Error Message
     */
    error_message?: string | null;
    /**
     * Input
     */
    input: {
        [key: string]: unknown;
    };
    /**
     * Kind
     */
    kind: string;
    /**
     * Max Attempts
     */
    max_attempts?: number;
    /**
     * Model
     */
    model: string;
    /**
     * Output
     */
    output?: {
        [key: string]: unknown;
    } | null;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Started At
     */
    started_at?: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Tool Calls
     */
    tool_calls?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Trace Id
     */
    trace_id: string;
    /**
     * Trigger
     */
    trigger: string;
};

/**
 * AiRunStatusChangedEnvelope
 */
export type AiRunStatusChangedEnvelope = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Event Id
     */
    event_id: string;
    /**
     * Occurred At
     */
    occurred_at: string;
    payload: AiRunStatusPayload;
    /**
     * Schema Version
     */
    schema_version?: '2.0';
    /**
     * Trace Id
     */
    trace_id?: string | null;
    /**
     * Type
     */
    type: 'ai.run.status_changed';
};

/**
 * AiRunStatusPayload
 */
export type AiRunStatusPayload = {
    /**
     * Error
     */
    error?: string | null;
    /**
     * Kind
     */
    kind: string;
    /**
     * Output
     */
    output?: {
        [key: string]: unknown;
    } | null;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Status
     */
    status: string;
};

/**
 * AutomationPolicyChangedEnvelope
 */
export type AutomationPolicyChangedEnvelope = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Event Id
     */
    event_id: string;
    /**
     * Occurred At
     */
    occurred_at: string;
    /**
     * Payload
     */
    payload: {
        [key: string]: unknown;
    };
    /**
     * Schema Version
     */
    schema_version?: '2.0';
    /**
     * Trace Id
     */
    trace_id?: string | null;
    /**
     * Type
     */
    type: 'automation.policy.changed';
};

/**
 * AutomationPolicyIn
 */
export type AutomationPolicyIn = {
    /**
     * Enabled
     */
    enabled?: boolean | null;
    /**
     * Event Trigger Enabled
     */
    event_trigger_enabled?: boolean | null;
    /**
     * Execution Mode
     */
    execution_mode?: 'automatic' | null;
    /**
     * Patrol Enabled
     */
    patrol_enabled?: boolean | null;
    /**
     * Patrol Force Interval Seconds
     */
    patrol_force_interval_seconds?: number | null;
    /**
     * Patrol Interval Seconds
     */
    patrol_interval_seconds?: number | null;
    /**
     * Sedentary Threshold Seconds
     */
    sedentary_threshold_seconds?: number | null;
    /**
     * Sedentary Trigger Enabled
     */
    sedentary_trigger_enabled?: boolean | null;
    /**
     * Vision Interval Seconds
     */
    vision_interval_seconds?: number | null;
    /**
     * Vision Schedule Enabled
     */
    vision_schedule_enabled?: boolean | null;
};

/**
 * AutomationPolicyOut
 */
export type AutomationPolicyOut = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Event Trigger Enabled
     */
    event_trigger_enabled: boolean;
    /**
     * Execution Mode
     */
    execution_mode: 'automatic';
    /**
     * Last Checked At
     */
    last_checked_at?: string | null;
    /**
     * Last Model Run At
     */
    last_model_run_at?: string | null;
    /**
     * Patrol Enabled
     */
    patrol_enabled: boolean;
    /**
     * Patrol Force Interval Seconds
     */
    patrol_force_interval_seconds: number;
    /**
     * Patrol Interval Seconds
     */
    patrol_interval_seconds: number;
    /**
     * Sedentary Threshold Seconds
     */
    sedentary_threshold_seconds: number;
    /**
     * Sedentary Trigger Enabled
     */
    sedentary_trigger_enabled: boolean;
    /**
     * Thresholds
     */
    thresholds: {
        [key: string]: number;
    };
    /**
     * Vision Interval Seconds
     */
    vision_interval_seconds: number;
    /**
     * Vision Schedule Enabled
     */
    vision_schedule_enabled: boolean;
};

/**
 * Body_upload_image
 */
export type BodyUploadImage = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * CapabilityCommandOut
 */
export type CapabilityCommandOut = {
    /**
     * Ai Allowed
     */
    ai_allowed?: boolean;
    /**
     * Name
     */
    name: string;
    /**
     * Parameter Schema
     */
    parameter_schema: {
        [key: string]: unknown;
    };
    /**
     * Safety Class
     */
    safety_class: 'normal' | 'safety' | 'administrative';
};

/**
 * CommandCreateV1
 */
export type CommandCreateV1 = {
    /**
     * Expires At
     */
    expires_at?: string | null;
    /**
     * Idempotency Key
     */
    idempotency_key?: string | null;
    /**
     * Parameter
     */
    parameter?: {
        [key: string]: unknown;
    };
    /**
     * Reason
     */
    reason?: string;
    /**
     * Type
     */
    type: string;
};

/**
 * CommandOut
 */
export type CommandOut = {
    /**
     * Command Id
     */
    command_id: string;
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Executed At
     */
    executed_at?: string | null;
    /**
     * Parameter
     */
    parameter?: {
        [key: string]: unknown;
    };
    /**
     * Published At
     */
    published_at?: string | null;
    /**
     * Reason
     */
    reason: string;
    /**
     * Source
     */
    source: string;
    /**
     * Status
     */
    status: string;
    /**
     * Type
     */
    type: string;
};

/**
 * CommandStatusChangedEnvelope
 */
export type CommandStatusChangedEnvelope = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Event Id
     */
    event_id: string;
    /**
     * Occurred At
     */
    occurred_at: string;
    payload: CommandStatusPayload;
    /**
     * Schema Version
     */
    schema_version?: '2.0';
    /**
     * Trace Id
     */
    trace_id?: string | null;
    /**
     * Type
     */
    type: 'command.status_changed';
};

/**
 * CommandStatusPayload
 */
export type CommandStatusPayload = {
    /**
     * Command Id
     */
    command_id: string;
    /**
     * Completed At
     */
    completed_at?: string | null;
    /**
     * Error Code
     */
    error_code?: string | null;
    /**
     * Executed At
     */
    executed_at?: string | null;
    /**
     * Message
     */
    message?: string;
    /**
     * Status
     */
    status: string;
    /**
     * Type
     */
    type?: string | null;
    [key: string]: unknown;
};

/**
 * CommandV1Out
 */
export type CommandV1Out = {
    /**
     * Accepted At
     */
    accepted_at?: string | null;
    /**
     * Capability
     */
    capability?: {
        [key: string]: unknown;
    } | null;
    /**
     * Command Id
     */
    command_id: string;
    /**
     * Completed At
     */
    completed_at?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Error Code
     */
    error_code?: string | null;
    /**
     * Expires At
     */
    expires_at?: string | null;
    /**
     * Parameter
     */
    parameter: {
        [key: string]: unknown;
    };
    /**
     * Published At
     */
    published_at?: string | null;
    /**
     * Reason
     */
    reason: string;
    /**
     * Source
     */
    source: string;
    /**
     * Status
     */
    status: string;
    /**
     * Trace Id
     */
    trace_id: string;
    /**
     * Type
     */
    type: string;
};

/**
 * DeviceCapabilitiesChangedEnvelope
 */
export type DeviceCapabilitiesChangedEnvelope = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Event Id
     */
    event_id: string;
    /**
     * Occurred At
     */
    occurred_at: string;
    /**
     * Payload
     */
    payload: {
        [key: string]: unknown;
    };
    /**
     * Schema Version
     */
    schema_version?: '2.0';
    /**
     * Trace Id
     */
    trace_id?: string | null;
    /**
     * Type
     */
    type: 'device.capabilities_changed';
};

/**
 * DeviceCapabilitiesOut
 */
export type DeviceCapabilitiesOut = {
    /**
     * Commands
     */
    commands: Array<CapabilityCommandOut>;
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Firmware Version
     */
    firmware_version: string;
    /**
     * Hardware Model
     */
    hardware_model: string;
    /**
     * Protocol Version
     */
    protocol_version: string;
    /**
     * Seen At
     */
    seen_at?: string | null;
};

/**
 * DeviceStatePayload
 */
export type DeviceStatePayload = {
    /**
     * Alarm On
     */
    alarm_on?: boolean | null;
    /**
     * Control Priority
     */
    control_priority?: 'manual_first' | 'auto_first' | null;
    /**
     * Led On
     */
    led_on?: boolean | null;
    /**
     * Manual Led Override
     */
    manual_led_override?: boolean | null;
    /**
     * Manual Override
     */
    manual_override?: boolean | null;
    /**
     * Manual Window Override
     */
    manual_window_override?: boolean | null;
    /**
     * Smoke Silenced
     */
    smoke_silenced?: boolean | null;
    /**
     * Window Open
     */
    window_open?: boolean | null;
};

/**
 * DeviceStatusChangedEnvelope
 */
export type DeviceStatusChangedEnvelope = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Event Id
     */
    event_id: string;
    /**
     * Occurred At
     */
    occurred_at: string;
    payload: StatusPayload;
    /**
     * Schema Version
     */
    schema_version?: '2.0';
    /**
     * Trace Id
     */
    trace_id?: string | null;
    /**
     * Type
     */
    type: 'device.status_changed';
};

/**
 * DeviceSummary
 */
export type DeviceSummary = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Last Seen At
     */
    last_seen_at?: string | null;
    /**
     * Status
     */
    status: string;
};

/**
 * ErrorPayload
 */
export type ErrorPayload = {
    /**
     * Code
     */
    code?: string;
    /**
     * Message
     */
    message: string;
    /**
     * Payload
     */
    payload?: {
        [key: string]: unknown;
    };
    /**
     * Topic
     */
    topic?: string | null;
};

/**
 * EventOut
 */
export type EventOut = {
    /**
     * Acknowledged At
     */
    acknowledged_at?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Id
     */
    id: number;
    /**
     * Message
     */
    message: string;
    /**
     * Severity
     */
    severity: string;
    /**
     * Type
     */
    type: string;
};

/**
 * FusionSnapshot
 */
export type FusionSnapshot = {
    /**
     * Air Quality
     */
    air_quality?: string | null;
    /**
     * Alarm Enabled
     */
    alarm_enabled?: boolean | null;
    /**
     * Reason
     */
    reason?: string | null;
    /**
     * Recommend Open Window
     */
    recommend_open_window?: boolean | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthOut
 */
export type HealthOut = {
    /**
     * Service
     */
    service: string;
    /**
     * Status
     */
    status: string;
};

/**
 * ImageAssetOut
 */
export type ImageAssetOut = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Id
     */
    id: number;
    /**
     * Url
     */
    url: string;
};

/**
 * ImageSnapshot
 */
export type ImageSnapshot = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: number;
    /**
     * Url
     */
    url: string;
};

/**
 * LatestState
 */
export type LatestState = {
    command?: CommandOut | null;
    device: DeviceSummary;
    image?: ImageSnapshot | null;
    pose?: PoseSnapshot | null;
    telemetry?: TelemetryPoint | null;
};

/**
 * NotificationCreatedEnvelope
 */
export type NotificationCreatedEnvelope = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Event Id
     */
    event_id: string;
    /**
     * Occurred At
     */
    occurred_at: string;
    payload: NotificationOut;
    /**
     * Schema Version
     */
    schema_version?: '2.0';
    /**
     * Trace Id
     */
    trace_id?: string | null;
    /**
     * Type
     */
    type: 'notification.created';
};

/**
 * NotificationIn
 */
export type NotificationIn = {
    /**
     * Content
     */
    content: string;
    /**
     * Voice Broadcast
     */
    voice_broadcast?: boolean;
};

/**
 * NotificationOut
 */
export type NotificationOut = {
    /**
     * Content
     */
    content: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Id
     */
    id: number;
    /**
     * Voice Command Id
     */
    voice_command_id?: string | null;
    /**
     * Voice Requested
     */
    voice_requested: boolean;
    /**
     * Voice Status
     */
    voice_status: 'not_requested' | 'unavailable' | 'pending' | 'executed' | 'rejected' | 'failed';
};

/**
 * PerceptionPayload
 */
export type PerceptionPayload = {
    /**
     * Kind
     */
    kind: 'image' | 'pose' | 'event' | 'log';
    [key: string]: unknown;
};

/**
 * PerceptionUpdatedEnvelope
 */
export type PerceptionUpdatedEnvelope = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Event Id
     */
    event_id: string;
    /**
     * Occurred At
     */
    occurred_at: string;
    payload: PerceptionPayload;
    /**
     * Schema Version
     */
    schema_version?: '2.0';
    /**
     * Trace Id
     */
    trace_id?: string | null;
    /**
     * Type
     */
    type: 'perception.updated';
};

/**
 * PoseAnalyzeAccepted
 */
export type PoseAnalyzeAccepted = {
    /**
     * Queued
     */
    queued: boolean;
    /**
     * Source Image Id
     */
    source_image_id: number;
};

/**
 * PoseSnapshot
 */
export type PoseSnapshot = {
    /**
     * Annotated Image Url
     */
    annotated_image_url?: string | null;
    /**
     * Body Coverage
     */
    body_coverage: 'upper_body' | 'full_body' | 'insufficient';
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Human Present
     */
    human_present: boolean;
    /**
     * Id
     */
    id: number;
    /**
     * Label
     */
    label: string;
    /**
     * Posture Code
     */
    posture_code: 'upright' | 'forward_lean' | 'hunched' | 'head_down' | 'not_seated' | 'unknown';
    /**
     * Posture Confidence
     */
    posture_confidence: number;
    /**
     * Posture Fresh
     */
    posture_fresh: boolean;
    /**
     * Posture Issues
     */
    posture_issues: Array<'forward_lean' | 'hunched' | 'head_down'>;
    /**
     * Presence Confidence
     */
    presence_confidence: number;
    /**
     * Presence Source
     */
    presence_source: 'object_detector' | 'pose_fallback' | 'none' | 'error';
    /**
     * Seated State
     */
    seated_state: 'seated' | 'not_seated' | 'unknown';
    /**
     * Source Image Url
     */
    source_image_url: string;
};

/**
 * SensorPayload
 */
export type SensorPayload = {
    /**
     * Eco2 Ppm
     */
    eco2_ppm?: number | null;
    /**
     * Hcho Ug M3
     */
    hcho_ug_m3?: number | null;
    /**
     * Humidity Percent
     */
    humidity_percent?: number | null;
    /**
     * Light Is Dark
     */
    light_is_dark?: boolean | null;
    /**
     * Smoke Detected
     */
    smoke_detected?: boolean | null;
    /**
     * Temperature C
     */
    temperature_c?: number | null;
    /**
     * Tvoc Ppb
     */
    tvoc_ppb?: number | null;
};

/**
 * StatusPayload
 */
export type StatusPayload = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Last Seen At
     */
    last_seen_at?: string | null;
    /**
     * Status
     */
    status: string;
};

/**
 * SystemErrorEnvelope
 */
export type SystemErrorEnvelope = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Event Id
     */
    event_id: string;
    /**
     * Occurred At
     */
    occurred_at: string;
    payload: ErrorPayload;
    /**
     * Schema Version
     */
    schema_version?: '2.0';
    /**
     * Trace Id
     */
    trace_id?: string | null;
    /**
     * Type
     */
    type: 'system.error';
};

/**
 * TelemetryBucketPoint
 *
 * time_bucket 降采样后的遥测聚合点（数值取均值，布尔取或，air_quality 取最差档）。
 */
export type TelemetryBucketPoint = {
    /**
     * Air Quality
     */
    air_quality?: string | null;
    /**
     * Alarm On
     */
    alarm_on?: boolean | null;
    /**
     * Bucket
     */
    bucket: string;
    /**
     * Eco2 Max Ppm
     */
    eco2_max_ppm?: number | null;
    /**
     * Eco2 Ppm
     */
    eco2_ppm?: number | null;
    /**
     * Hcho Ug M3
     */
    hcho_ug_m3?: number | null;
    /**
     * Humidity Max Percent
     */
    humidity_max_percent?: number | null;
    /**
     * Humidity Min Percent
     */
    humidity_min_percent?: number | null;
    /**
     * Humidity Percent
     */
    humidity_percent?: number | null;
    /**
     * Led On
     */
    led_on?: boolean | null;
    /**
     * Light Is Dark
     */
    light_is_dark?: boolean | null;
    /**
     * Sample Count
     */
    sample_count: number;
    /**
     * Smoke Detected
     */
    smoke_detected?: boolean | null;
    /**
     * Temperature C
     */
    temperature_c?: number | null;
    /**
     * Temperature Max C
     */
    temperature_max_c?: number | null;
    /**
     * Temperature Min C
     */
    temperature_min_c?: number | null;
    /**
     * Tvoc Ppb
     */
    tvoc_ppb?: number | null;
    /**
     * Window Open
     */
    window_open?: boolean | null;
};

/**
 * TelemetryPoint
 */
export type TelemetryPoint = {
    /**
     * Device Id
     */
    device_id: string;
    fusion: FusionSnapshot;
    /**
     * Sampled At
     */
    sampled_at: string;
    sensors: SensorPayload;
    state: DeviceStatePayload;
};

/**
 * TelemetryReceivedEnvelope
 */
export type TelemetryReceivedEnvelope = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Event Id
     */
    event_id: string;
    /**
     * Occurred At
     */
    occurred_at: string;
    payload: TelemetryPoint;
    /**
     * Schema Version
     */
    schema_version?: '2.0';
    /**
     * Trace Id
     */
    trace_id?: string | null;
    /**
     * Type
     */
    type: 'telemetry.received';
};

/**
 * TraceEventOut
 */
export type TraceEventOut = {
    /**
     * Component
     */
    component: string;
    /**
     * Detail
     */
    detail: {
        [key: string]: unknown;
    };
    /**
     * Device Id
     */
    device_id?: string | null;
    /**
     * Event Id
     */
    event_id: string;
    /**
     * Event Type
     */
    event_type: string;
    /**
     * Occurred At
     */
    occurred_at: string;
    /**
     * Status
     */
    status?: string | null;
};

/**
 * TraceTimelineOut
 */
export type TraceTimelineOut = {
    /**
     * Events
     */
    events?: Array<TraceEventOut>;
    /**
     * Trace Id
     */
    trace_id: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type WsMessage = ({
    type: 'telemetry.received';
} & TelemetryReceivedEnvelope) | ({
    type: 'device.status_changed';
} & DeviceStatusChangedEnvelope) | ({
    type: 'perception.updated';
} & PerceptionUpdatedEnvelope) | ({
    type: 'command.status_changed';
} & CommandStatusChangedEnvelope) | ({
    type: 'ai.run.status_changed';
} & AiRunStatusChangedEnvelope) | ({
    type: 'notification.created';
} & NotificationCreatedEnvelope) | ({
    type: 'device.capabilities_changed';
} & DeviceCapabilitiesChangedEnvelope) | ({
    type: 'automation.policy.changed';
} & AutomationPolicyChangedEnvelope) | ({
    type: 'system.error';
} & SystemErrorEnvelope);

export type ListDevicesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/devices';
};

export type ListDevicesResponses = {
    /**
     * Response List Devices
     *
     * Successful Response
     */
    200: Array<DeviceSummary>;
};

export type ListDevicesResponse = ListDevicesResponses[keyof ListDevicesResponses];

export type ListAiRunsData = {
    body?: never;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: {
        /**
         * Kind
         */
        kind?: string | null;
        /**
         * Status
         */
        status?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/devices/{device_id}/ai/runs';
};

export type ListAiRunsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAiRunsError = ListAiRunsErrors[keyof ListAiRunsErrors];

export type ListAiRunsResponses = {
    /**
     * Response List Ai Runs
     *
     * Successful Response
     */
    200: Array<AiRunOut>;
};

export type ListAiRunsResponse = ListAiRunsResponses[keyof ListAiRunsResponses];

export type CreateAiRunData = {
    body: AiRunCreate;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: never;
    url: '/api/v1/devices/{device_id}/ai/runs';
};

export type CreateAiRunErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAiRunError = CreateAiRunErrors[keyof CreateAiRunErrors];

export type CreateAiRunResponses = {
    /**
     * Successful Response
     */
    202: AiRunOut;
};

export type CreateAiRunResponse = CreateAiRunResponses[keyof CreateAiRunResponses];

export type GetAiRunData = {
    body?: never;
    path: {
        /**
         * Device Id
         */
        device_id: string;
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/devices/{device_id}/ai/runs/{run_id}';
};

export type GetAiRunErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAiRunError = GetAiRunErrors[keyof GetAiRunErrors];

export type GetAiRunResponses = {
    /**
     * Successful Response
     */
    200: AiRunOut;
};

export type GetAiRunResponse = GetAiRunResponses[keyof GetAiRunResponses];

export type CancelAiRunData = {
    body?: never;
    path: {
        /**
         * Device Id
         */
        device_id: string;
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/devices/{device_id}/ai/runs/{run_id}/cancel';
};

export type CancelAiRunErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelAiRunError = CancelAiRunErrors[keyof CancelAiRunErrors];

export type CancelAiRunResponses = {
    /**
     * Successful Response
     */
    200: AiRunOut;
};

export type CancelAiRunResponse = CancelAiRunResponses[keyof CancelAiRunResponses];

export type GetAutomationPolicyData = {
    body?: never;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: never;
    url: '/api/v1/devices/{device_id}/automation-policy';
};

export type GetAutomationPolicyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAutomationPolicyError = GetAutomationPolicyErrors[keyof GetAutomationPolicyErrors];

export type GetAutomationPolicyResponses = {
    /**
     * Successful Response
     */
    200: AutomationPolicyOut;
};

export type GetAutomationPolicyResponse = GetAutomationPolicyResponses[keyof GetAutomationPolicyResponses];

export type UpdateAutomationPolicyData = {
    body: AutomationPolicyIn;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: never;
    url: '/api/v1/devices/{device_id}/automation-policy';
};

export type UpdateAutomationPolicyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAutomationPolicyError = UpdateAutomationPolicyErrors[keyof UpdateAutomationPolicyErrors];

export type UpdateAutomationPolicyResponses = {
    /**
     * Successful Response
     */
    200: AutomationPolicyOut;
};

export type UpdateAutomationPolicyResponse = UpdateAutomationPolicyResponses[keyof UpdateAutomationPolicyResponses];

export type GetDeviceCapabilitiesData = {
    body?: never;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: never;
    url: '/api/v1/devices/{device_id}/capabilities';
};

export type GetDeviceCapabilitiesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDeviceCapabilitiesError = GetDeviceCapabilitiesErrors[keyof GetDeviceCapabilitiesErrors];

export type GetDeviceCapabilitiesResponses = {
    /**
     * Successful Response
     */
    200: DeviceCapabilitiesOut;
};

export type GetDeviceCapabilitiesResponse = GetDeviceCapabilitiesResponses[keyof GetDeviceCapabilitiesResponses];

export type SendCommandData = {
    body: CommandCreateV1;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: never;
    url: '/api/v1/devices/{device_id}/commands';
};

export type SendCommandErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendCommandError = SendCommandErrors[keyof SendCommandErrors];

export type SendCommandResponses = {
    /**
     * Successful Response
     */
    202: CommandV1Out;
};

export type SendCommandResponse = SendCommandResponses[keyof SendCommandResponses];

export type GetCommandV1Data = {
    body?: never;
    path: {
        /**
         * Device Id
         */
        device_id: string;
        /**
         * Command Id
         */
        command_id: string;
    };
    query?: never;
    url: '/api/v1/devices/{device_id}/commands/{command_id}';
};

export type GetCommandV1Errors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCommandV1Error = GetCommandV1Errors[keyof GetCommandV1Errors];

export type GetCommandV1Responses = {
    /**
     * Successful Response
     */
    200: CommandV1Out;
};

export type GetCommandV1Response = GetCommandV1Responses[keyof GetCommandV1Responses];

export type DeviceEventsData = {
    body?: never;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/devices/{device_id}/events';
};

export type DeviceEventsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeviceEventsError = DeviceEventsErrors[keyof DeviceEventsErrors];

export type DeviceEventsResponses = {
    /**
     * Response Device Events
     *
     * Successful Response
     */
    200: Array<EventOut>;
};

export type DeviceEventsResponse = DeviceEventsResponses[keyof DeviceEventsResponses];

export type AckDeviceEventData = {
    body?: never;
    path: {
        /**
         * Device Id
         */
        device_id: string;
        /**
         * Event Id
         */
        event_id: number;
    };
    query?: never;
    url: '/api/v1/devices/{device_id}/events/{event_id}/ack';
};

export type AckDeviceEventErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AckDeviceEventError = AckDeviceEventErrors[keyof AckDeviceEventErrors];

export type AckDeviceEventResponses = {
    /**
     * Successful Response
     */
    200: EventOut;
};

export type AckDeviceEventResponse = AckDeviceEventResponses[keyof AckDeviceEventResponses];

export type TelemetryHistoryData = {
    body?: never;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/devices/{device_id}/history';
};

export type TelemetryHistoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TelemetryHistoryError = TelemetryHistoryErrors[keyof TelemetryHistoryErrors];

export type TelemetryHistoryResponses = {
    /**
     * Response Telemetry History
     *
     * Successful Response
     */
    200: Array<TelemetryPoint>;
};

export type TelemetryHistoryResponse = TelemetryHistoryResponses[keyof TelemetryHistoryResponses];

export type TelemetryHistoryBucketedData = {
    body?: never;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: {
        /**
         * Bucket
         *
         * 降采样窗口秒数
         */
        bucket?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/devices/{device_id}/history/bucketed';
};

export type TelemetryHistoryBucketedErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TelemetryHistoryBucketedError = TelemetryHistoryBucketedErrors[keyof TelemetryHistoryBucketedErrors];

export type TelemetryHistoryBucketedResponses = {
    /**
     * Response Telemetry History Bucketed
     *
     * Successful Response
     */
    200: Array<TelemetryBucketPoint>;
};

export type TelemetryHistoryBucketedResponse = TelemetryHistoryBucketedResponses[keyof TelemetryHistoryBucketedResponses];

export type UploadImageData = {
    body: BodyUploadImage;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: never;
    url: '/api/v1/devices/{device_id}/images';
};

export type UploadImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadImageError = UploadImageErrors[keyof UploadImageErrors];

export type UploadImageResponses = {
    /**
     * Successful Response
     */
    200: ImageAssetOut;
};

export type UploadImageResponse = UploadImageResponses[keyof UploadImageResponses];

export type LatestDeviceStateData = {
    body?: never;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: never;
    url: '/api/v1/devices/{device_id}/latest';
};

export type LatestDeviceStateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LatestDeviceStateError = LatestDeviceStateErrors[keyof LatestDeviceStateErrors];

export type LatestDeviceStateResponses = {
    /**
     * Successful Response
     */
    200: LatestState;
};

export type LatestDeviceStateResponse = LatestDeviceStateResponses[keyof LatestDeviceStateResponses];

export type DeviceNotificationsData = {
    body?: never;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/devices/{device_id}/notifications';
};

export type DeviceNotificationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeviceNotificationsError = DeviceNotificationsErrors[keyof DeviceNotificationsErrors];

export type DeviceNotificationsResponses = {
    /**
     * Response Device Notifications
     *
     * Successful Response
     */
    200: Array<NotificationOut>;
};

export type DeviceNotificationsResponse = DeviceNotificationsResponses[keyof DeviceNotificationsResponses];

export type SendNotificationData = {
    body: NotificationIn;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: never;
    url: '/api/v1/devices/{device_id}/notifications';
};

export type SendNotificationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendNotificationError = SendNotificationErrors[keyof SendNotificationErrors];

export type SendNotificationResponses = {
    /**
     * Successful Response
     */
    201: NotificationOut;
};

export type SendNotificationResponse = SendNotificationResponses[keyof SendNotificationResponses];

export type AnalyzeLatestPoseData = {
    body?: never;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: never;
    url: '/api/v1/devices/{device_id}/pose/analyze';
};

export type AnalyzeLatestPoseErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalyzeLatestPoseError = AnalyzeLatestPoseErrors[keyof AnalyzeLatestPoseErrors];

export type AnalyzeLatestPoseResponses = {
    /**
     * Successful Response
     */
    202: PoseAnalyzeAccepted;
};

export type AnalyzeLatestPoseResponse = AnalyzeLatestPoseResponses[keyof AnalyzeLatestPoseResponses];

export type GetTraceTimelineData = {
    body?: never;
    path: {
        /**
         * Trace Id
         */
        trace_id: string;
    };
    query?: never;
    url: '/api/v1/diagnostics/traces/{trace_id}';
};

export type GetTraceTimelineErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTraceTimelineError = GetTraceTimelineErrors[keyof GetTraceTimelineErrors];

export type GetTraceTimelineResponses = {
    /**
     * Successful Response
     */
    200: TraceTimelineOut;
};

export type GetTraceTimelineResponse = GetTraceTimelineResponses[keyof GetTraceTimelineResponses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthResponses = {
    /**
     * Successful Response
     */
    200: HealthOut;
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type HealthLiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/live';
};

export type HealthLiveResponses = {
    /**
     * Successful Response
     */
    200: HealthOut;
};

export type HealthLiveResponse = HealthLiveResponses[keyof HealthLiveResponses];

export type HealthReadyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type HealthReadyResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
