#pragma once

#include "sdkconfig.h"

/* ESP-IDF leaves disabled bool Kconfig symbols undefined. */
#ifndef CONFIG_APP_SENSOR_MOCK_ENABLED
#define CONFIG_APP_SENSOR_MOCK_ENABLED 0
#endif

#ifndef CONFIG_APP_WIFI_ENABLED
#define CONFIG_APP_WIFI_ENABLED 0
#endif

#ifndef CONFIG_APP_MQTT_ENABLED
#define CONFIG_APP_MQTT_ENABLED 0
#endif

#ifndef CONFIG_APP_IMAGE_UPLOAD_ENABLED
#define CONFIG_APP_IMAGE_UPLOAD_ENABLED 0
#endif

#ifndef CONFIG_APP_CAMERA_ENABLED
#define CONFIG_APP_CAMERA_ENABLED 0
#endif

#ifndef CONFIG_APP_DISPLAY_ENABLED
#define CONFIG_APP_DISPLAY_ENABLED 0
#endif

#ifndef CONFIG_APP_ACTUATOR_ENABLED
#define CONFIG_APP_ACTUATOR_ENABLED 0
#endif

#ifndef CONFIG_APP_BUTTON_ENABLED
#define CONFIG_APP_BUTTON_ENABLED 0
#endif

#ifndef CONFIG_APP_BEEP_ACTIVE_LOW
#define CONFIG_APP_BEEP_ACTIVE_LOW 0
#endif

#ifndef CONFIG_APP_MQ2_ENABLED
#define CONFIG_APP_MQ2_ENABLED 0
#endif

#ifndef CONFIG_APP_MQ2_ACTIVE_LOW
#define CONFIG_APP_MQ2_ACTIVE_LOW 0
#endif

#ifndef CONFIG_APP_VOICE_ENABLED
#define CONFIG_APP_VOICE_ENABLED 0
#endif

#ifndef CONFIG_APP_LED_MODE_GPIO
#define CONFIG_APP_LED_MODE_GPIO 0
#endif

#ifndef CONFIG_APP_LED_ACTIVE_LOW
#define CONFIG_APP_LED_ACTIVE_LOW 0
#endif

#ifndef CONFIG_APP_LED_GPIO
#define CONFIG_APP_LED_GPIO 0
#endif
