/* Generated from contracts/firmware-behavior.json. Do not edit by hand. */
#pragma once

#define AIOT_FIRMWARE_BEHAVIOR_VERSION "1.0"
#define AIOT_FUSION_TEMPERATURE_WATCH_C 28.0f
#define AIOT_FUSION_TEMPERATURE_ALERT_C 32.0f
#define AIOT_FUSION_HUMIDITY_LOW_PERCENT 30.0f
#define AIOT_FUSION_HUMIDITY_HIGH_PERCENT 75.0f
#define AIOT_FUSION_TVOC_WATCH_PPB 300U
#define AIOT_FUSION_TVOC_ALERT_PPB 600U
#define AIOT_FUSION_HCHO_WATCH_UG_M3 60U
#define AIOT_FUSION_HCHO_ALERT_UG_M3 100U
#define AIOT_FUSION_ECO2_WATCH_PPM 1000U
#define AIOT_FUSION_ECO2_ALERT_PPM 1500U
#define AIOT_COMMAND_QUEUE_LENGTH 4U
#define AIOT_TERMINAL_ACK_CACHE_SIZE 16U
#define AIOT_SMOKE_SILENCE_MIN_SECONDS 10U
#define AIOT_SMOKE_SILENCE_MAX_SECONDS 600U
#define AIOT_SMOKE_REANNOUNCE_SECONDS 30U
#define AIOT_SMOKE_CLEAR_STABLE_MS 1000U
#define AIOT_VOICE_LOCAL_RETRY_ATTEMPTS 3U
#define AIOT_VOICE_RETRY_BACKOFF_MS 250U
#define AIOT_VOICE_TX_TIMEOUT_MS 1000U
#define AIOT_COMMAND_EXECUTION_PERIOD_MS 500U
