[CmdletBinding()]
param(
    [ValidateSet("MockDemo", "DeviceDemo", "LlmDemo")]
    [string] $Preset = "MockDemo",

    [switch] $Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$RepoRoot = Split-Path -Parent $PSScriptRoot
$ComposeEnvPath = Join-Path $RepoRoot ".env"
$ServerEnvPath = Join-Path $RepoRoot "server\.env"
$WebEnvPath = Join-Path $RepoRoot "web\.env.local"
$DeviceIdDefault = "esp32s3-001"

function Get-DefaultLanAddress {
    try {
        $addresses = Get-NetIPAddress -AddressFamily IPv4 |
            Where-Object {
                $_.IPAddress -ne "127.0.0.1" -and
                $_.IPAddress -notlike "169.254.*" -and
                $_.PrefixOrigin -in @("Dhcp", "Manual")
            } |
            Sort-Object InterfaceMetric, InterfaceIndex

        if ($addresses) {
            return $addresses[0].IPAddress
        }
    } catch {
        return "127.0.0.1"
    }

    return "127.0.0.1"
}

function Read-Value {
    param(
        [Parameter(Mandatory = $true)]
        [string] $Prompt,

        [Parameter(Mandatory = $true)]
        [string] $Default
    )

    $raw = Read-Host "$Prompt [$Default]"
    if ([string]::IsNullOrWhiteSpace($raw)) {
        return $Default
    }

    return $raw.Trim()
}

function Read-YesNo {
    param(
        [Parameter(Mandatory = $true)]
        [string] $Prompt,

        [bool] $Default = $true
    )

    $hint = if ($Default) { "Y/n" } else { "y/N" }
    while ($true) {
        $raw = Read-Host "$Prompt [$hint]"
        if ([string]::IsNullOrWhiteSpace($raw)) {
            return $Default
        }

        switch -Regex ($raw.Trim()) {
            "^(y|yes|true|1|shi|是)$" { return $true }
            "^(n|no|false|0|bu|否)$" { return $false }
            default { Write-Host "Please answer y or n." -ForegroundColor Yellow }
        }
    }
}

function Read-SecretPlainText {
    param(
        [Parameter(Mandatory = $true)]
        [string] $Prompt
    )

    $secure = Read-Host $Prompt -AsSecureString
    if ($null -eq $secure -or $secure.Length -eq 0) {
        return ""
    }

    return [System.Net.NetworkCredential]::new("", $secure).Password
}

function ConvertTo-EnvValue {
    param(
        [AllowNull()]
        [object] $Value
    )

    if ($null -eq $Value) {
        return ""
    }

    return [string] $Value
}

function Backup-IfNeeded {
    param(
        [Parameter(Mandatory = $true)]
        [string] $Path
    )

    if (-not (Test-Path -LiteralPath $Path)) {
        return
    }

    if (-not $Force) {
        $overwrite = Read-YesNo -Prompt "Local config exists at $Path. Back up and overwrite it?" -Default $false
        if (-not $overwrite) {
            throw "Canceled before overwriting $Path."
        }
    }

    $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $backupPath = "$Path.bak.$timestamp"
    Copy-Item -LiteralPath $Path -Destination $backupPath -Force
    Write-Host "Backed up $Path to $backupPath" -ForegroundColor DarkGray
}

function Write-LocalEnvFile {
    param(
        [Parameter(Mandatory = $true)]
        [string] $Path,

        [Parameter(Mandatory = $true)]
        [AllowEmptyString()]
        [string[]] $Lines
    )

    $directory = Split-Path -Parent $Path
    if (-not (Test-Path -LiteralPath $directory)) {
        New-Item -ItemType Directory -Path $directory | Out-Null
    }

    Backup-IfNeeded -Path $Path
    Set-Content -LiteralPath $Path -Value $Lines -Encoding utf8
    Write-Host "Wrote $Path" -ForegroundColor Green
}

function New-ServerEnvLines {
    param(
        [Parameter(Mandatory = $true)]
        [hashtable] $Config
    )

    $orderedKeys = @(
        "AIOT_APP_ENV",
        "AIOT_DATABASE_URL",
        "AIOT_AUTO_CREATE_TABLES",
        "AIOT_BASE_URL",
        "AIOT_UPLOADS_DIR",
        "AIOT_MAX_UPLOAD_BYTES",
        "AIOT_MQTT_ENABLED",
        "AIOT_MQTT_HOST",
        "AIOT_MQTT_PORT",
        "AIOT_MQTT_CLIENT_ID",
        "AIOT_MQTT_USERNAME",
        "AIOT_MQTT_PASSWORD",
        "AIOT_MQTT_RECONNECT_SECONDS",
        "AIOT_CORS_ORIGINS",
        "AIOT_LLM_ENDPOINT",
        "AIOT_LLM_API_KEY",
        "AIOT_LLM_MODEL",
        "AIOT_LLM_TIMEOUT_SECONDS",
        "AIOT_LLM_VISION_ENABLED",
        "AIOT_LLM_IMAGE_MAX_AGE_SECONDS",
        "AIOT_LLM_RESPONSE_FORMAT",
        "AIOT_AUTOPILOT_ENABLED",
        "AIOT_AUTOPILOT_COOLDOWN_SECONDS",
        "AIOT_AUTOPILOT_MIN_CONFIDENCE",
        "AIOT_AUTOPILOT_TRIGGER_LEVELS"
    )

    $lines = @(
        "# Generated by tools/configure-local.ps1.",
        "# Local only. Do not commit real secrets.",
        ""
    )

    foreach ($key in $orderedKeys) {
        $lines += "$key=$(ConvertTo-EnvValue $Config[$key])"
    }

    return $lines
}

function New-ComposeEnvLines {
    param(
        [Parameter(Mandatory = $true)]
        [hashtable] $Config
    )

    $orderedKeys = @(
        "AIOT_LLM_ENDPOINT",
        "AIOT_LLM_API_KEY",
        "AIOT_LLM_MODEL",
        "AIOT_LLM_VISION_ENABLED",
        "AIOT_LLM_RESPONSE_FORMAT",
        "AIOT_AUTOPILOT_ENABLED",
        "AIOT_AUTOPILOT_COOLDOWN_SECONDS",
        "AIOT_AUTOPILOT_MIN_CONFIDENCE",
        "AIOT_AUTOPILOT_TRIGGER_LEVELS"
    )

    $lines = @(
        "# Generated by tools/configure-local.ps1.",
        "# Used by docker compose. Local only; do not commit real secrets.",
        ""
    )

    foreach ($key in $orderedKeys) {
        $lines += "$key=$(ConvertTo-EnvValue $Config[$key])"
    }

    return $lines
}

function Show-FirmwareHint {
    param(
        [Parameter(Mandatory = $true)]
        [string] $DeviceId,

        [Parameter(Mandatory = $true)]
        [string] $LanAddress
    )

    Write-Host ""
    Write-Host "Firmware menuconfig values for a real ESP32-S3 demo:" -ForegroundColor Cyan
    Write-Host "  APP_DEVICE_ID=$DeviceId"
    Write-Host "  APP_WIFI_ENABLED=y"
    Write-Host "  APP_MQTT_ENABLED=y"
    Write-Host "  APP_MQTT_BROKER_URI=mqtt://$LanAddress`:1883"
    Write-Host "  APP_IMAGE_UPLOAD_ENABLED=y"
    Write-Host "  APP_IMAGE_UPLOAD_URL=http://$LanAddress`:8000/api/devices/$DeviceId/images"
    Write-Host ""
    Write-Host "Open it from VS Code with: Tasks: Run Task -> 固件：打开图形化配置"
}

$lanAddress = Get-DefaultLanAddress
$deviceId = $DeviceIdDefault
$apiBaseUrl = "http://localhost:8000"
$serverBaseUrl = "http://127.0.0.1:8000"
$mqttHost = "127.0.0.1"
$llmEndpoint = "mock"
$llmApiKey = ""
$llmModel = "demo-model"
$llmVisionEnabled = "true"
$autopilotEnabled = "true"
$autopilotMinConfidence = "0.6"
$autopilotTriggerLevels = "alert"

switch ($Preset) {
    "MockDemo" {
        Write-Host "Configuring local offline demo with AIOT_LLM_ENDPOINT=mock." -ForegroundColor Cyan
    }
    "DeviceDemo" {
        Write-Host "Configuring real-device demo defaults." -ForegroundColor Cyan
        $deviceId = Read-Value -Prompt "Device ID" -Default $DeviceIdDefault
        $lanAddress = Read-Value -Prompt "This laptop LAN IP for ESP32-S3" -Default $lanAddress
        $serverBaseUrl = "http://$lanAddress`:8000"
        $mqttHost = $lanAddress
        $apiBaseUrl = Read-Value -Prompt "Web console API base URL" -Default "http://localhost:8000"
        $llmEndpoint = Read-Value -Prompt "LLM endpoint (use mock for offline demo)" -Default "mock"
        if ($llmEndpoint -ne "mock" -and -not [string]::IsNullOrWhiteSpace($llmEndpoint)) {
            $llmModel = Read-Value -Prompt "LLM model" -Default "demo-model"
            $llmApiKey = Read-SecretPlainText -Prompt "LLM API key (input hidden, leave empty if not needed)"
        }
        $llmVisionEnabled = if (Read-YesNo -Prompt "Attach latest JPEG to LLM requests?" -Default $true) { "true" } else { "false" }
        $autopilotEnabled = if (Read-YesNo -Prompt "Enable autopilot by default?" -Default $true) { "true" } else { "false" }
        $autopilotMinConfidence = Read-Value -Prompt "Autopilot minimum confidence" -Default "0.6"
        $autopilotTriggerLevels = Read-Value -Prompt "Autopilot trigger levels (comma-separated good/watch/alert)" -Default "alert"
    }
    "LlmDemo" {
        Write-Host "Configuring local demo with a real OpenAI-compatible LLM endpoint." -ForegroundColor Cyan
        $llmEndpoint = Read-Value -Prompt "LLM endpoint" -Default "https://api.openai.com/v1/chat/completions"
        $llmModel = Read-Value -Prompt "LLM model" -Default "gpt-4o-mini"
        $llmApiKey = Read-SecretPlainText -Prompt "LLM API key (input hidden)"
        $llmVisionEnabled = if (Read-YesNo -Prompt "Attach latest JPEG to LLM requests?" -Default $true) { "true" } else { "false" }
    }
}

$corsOrigins = @(
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://$lanAddress`:3000"
) | Select-Object -Unique

$serverConfig = @{
    AIOT_APP_ENV = "dev"
    AIOT_DATABASE_URL = "postgresql+psycopg://aiot:aiot@127.0.0.1:5432/aiot"
    AIOT_AUTO_CREATE_TABLES = "true"
    AIOT_BASE_URL = $serverBaseUrl
    AIOT_UPLOADS_DIR = "uploads"
    AIOT_MAX_UPLOAD_BYTES = "10485760"
    AIOT_MQTT_ENABLED = "true"
    AIOT_MQTT_HOST = $mqttHost
    AIOT_MQTT_PORT = "1883"
    AIOT_MQTT_CLIENT_ID = "aiot-gateway"
    AIOT_MQTT_USERNAME = ""
    AIOT_MQTT_PASSWORD = ""
    AIOT_MQTT_RECONNECT_SECONDS = "3"
    AIOT_CORS_ORIGINS = $corsOrigins -join ","
    AIOT_LLM_ENDPOINT = $llmEndpoint
    AIOT_LLM_API_KEY = $llmApiKey
    AIOT_LLM_MODEL = $llmModel
    AIOT_LLM_TIMEOUT_SECONDS = "12"
    AIOT_LLM_VISION_ENABLED = $llmVisionEnabled
    AIOT_LLM_IMAGE_MAX_AGE_SECONDS = "600"
    AIOT_LLM_RESPONSE_FORMAT = "json_object"
    AIOT_AUTOPILOT_ENABLED = $autopilotEnabled
    AIOT_AUTOPILOT_COOLDOWN_SECONDS = "120"
    AIOT_AUTOPILOT_MIN_CONFIDENCE = $autopilotMinConfidence
    AIOT_AUTOPILOT_TRIGGER_LEVELS = $autopilotTriggerLevels
}

$webLines = @(
    "# Generated by tools/configure-local.ps1.",
    "NEXT_PUBLIC_API_BASE_URL=$apiBaseUrl"
)

Write-LocalEnvFile -Path $ComposeEnvPath -Lines (New-ComposeEnvLines -Config $serverConfig)
Write-LocalEnvFile -Path $ServerEnvPath -Lines (New-ServerEnvLines -Config $serverConfig)
Write-LocalEnvFile -Path $WebEnvPath -Lines $webLines

Write-Host ""
Write-Host "Done. These files are ignored by Git:" -ForegroundColor Green
Write-Host "  .env"
Write-Host "  server\.env"
Write-Host "  web\.env.local"

if ($Preset -eq "DeviceDemo") {
    Show-FirmwareHint -DeviceId $deviceId -LanAddress $lanAddress
}
